### ISSUE TITLE
install on Mac

### ISSUE THREAD

**Issue by antoine4ucsd** [UNSW-Mathematical-Biology/NGlyAlign_v1.0#1]
Hello
I would be very interested in trying your tool. can it be deployed on a mac (or run online)?
thank you!

**Comment by UNSW-Mathematical-Biology** [comment]
Dear Antoine,
                       Thank you for your interest. My apology as due to the resource restriction, we are unable to it in mac or online. That is something we will try to resolve in the future.


Thanks,
Elma Akand
________________________________

**Comment by antoine4ucsd** [comment]
Thank you Elma
I understand. I was able to install it on a windows machine.
Would you have time to look at a set of HIV sequences (env). As you can guess, these can be tricky to align and I have very different results using mafft, praline, clustalw, hivalign (lanl), genecutter (lanl) or NGlyAlign.

Have a nice week

--
a

**Comment by antoine4ucsd** [comment]
Hello Elma
Would you have advices on praline setup for HIV FL length env. I am trying to optimize nucleotides alignment as much as possible and as you know, variable regions are really tricky.
I can share a couple of alignment if you have time.

Thank you!
--
a


From: A Chai ***@***.***>
Date: Monday, February 22, 2021 at 7:45 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Thank you Elma
I understand. I was able to install it on a windows machine.
Would you have time to look at a set of HIV sequences (env). As you can guess, these can be tricky to align and I have very different results using mafft, praline, clustalw, hivalign (lanl), genecutter (lanl) or NGlyAlign.

Have a nice week

--
a


From: Elma H. Akand ***@***.***>
Date: Monday, February 22, 2021 at 2:24 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: antoine ***@***.***>, Author ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Dear Antoine,
Thank you for your interest. My apology as due to the resource restriction, we are unable to it in mac or online. That is something we will try to resolve in the future.


Thanks,
Elma Akand
________________________________
From: antoine ***@***.***>
Sent: Saturday, 20 February 2021 7:16 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)


Hello
I would be very interested in trying your tool. can it be deployed on a mac (or run online)?
thank you!

**Comment by antoine4ucsd** [comment]
Hello Emma,
Just following up.
I am still trying to figure the best alignment method for my HIV sequences. I have both NGlyAlign and praline installed and I would like to compare overall performance with alignstat…
My alignments are HIV nucleotides FL env sequences.
Would you have suggestions on how to run NGlyalign to optimize alignment? And I saw you compared it with praline. which parameters did you use for the latter?

We can set up a quick call anytime and/or I can share one example dataset if you want.

Thank you


--
a


From: A Chai ***@***.***>
Date: Sunday, May 9, 2021 at 3:30 PM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Hello Elma
Would you have advices on praline setup for HIV FL length env. I am trying to optimize nucleotides alignment as much as possible and as you know, variable regions are really tricky.
I can share a couple of alignment if you have time.

Thank you!
--
a


From: A Chai ***@***.***>
Date: Monday, February 22, 2021 at 7:45 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Thank you Elma
I understand. I was able to install it on a windows machine.
Would you have time to look at a set of HIV sequences (env). As you can guess, these can be tricky to align and I have very different results using mafft, praline, clustalw, hivalign (lanl), genecutter (lanl) or NGlyAlign.

Have a nice week

--
a


From: Elma H. Akand ***@***.***>
Date: Monday, February 22, 2021 at 2:24 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: antoine ***@***.***>, Author ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Dear Antoine,
Thank you for your interest. My apology as due to the resource restriction, we are unable to it in mac or online. That is something we will try to resolve in the future.


Thanks,
Elma Akand
________________________________
From: antoine ***@***.***>
Sent: Saturday, 20 February 2021 7:16 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)


Hello
I would be very interested in trying your tool. can it be deployed on a mac (or run online)?
thank you!

**Comment by antoine4ucsd** [comment]
Hello Elma
I hope you are doing well
After being swamped by too many COVID projects, I am back on track with our HIV projects. I am still trying to optimize my HIV FL env alignment. I tried various approach from the most ‘popular’ (clustal, mafft) to prank, ma-praline and …glyalign.
The latter gives me good results and final aa alignment when running for a limited number of sequences (up to ~100) but when I merge all my participant data into one set (~950 sequences), it does not seem to run anymore  - i.e. glyalign is working but when I click next on the align panel, either nothing happen (I let it run for > 24 hours) or I get an error message. I posted this issue on github too.
I realize trying to align env sequences from multiple samples and multiple participants is a big challenge but I would like to try.

(I kept the default parameters but can change to BIOSUM and vary the threshold if you think it will be better)
If you are interested/if you have time, I would be happy to discuss our project with you.

Best,

--
a


From: A Chai ***@***.***>
Date: Sunday, May 16, 2021 at 9:27 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Hello Emma,
Just following up.
I am still trying to figure the best alignment method for my HIV sequences. I have both NGlyAlign and praline installed and I would like to compare overall performance with alignstat…
My alignments are HIV nucleotides FL env sequences.
Would you have suggestions on how to run NGlyalign to optimize alignment? And I saw you compared it with praline. which parameters did you use for the latter?

We can set up a quick call anytime and/or I can share one example dataset if you want.

Thank you


--
a


From: A Chai ***@***.***>
Date: Sunday, May 9, 2021 at 3:30 PM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Hello Elma
Would you have advices on praline setup for HIV FL length env. I am trying to optimize nucleotides alignment as much as possible and as you know, variable regions are really tricky.
I can share a couple of alignment if you have time.

Thank you!
--
a


From: A Chai ***@***.***>
Date: Monday, February 22, 2021 at 7:45 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Thank you Elma
I understand. I was able to install it on a windows machine.
Would you have time to look at a set of HIV sequences (env). As you can guess, these can be tricky to align and I have very different results using mafft, praline, clustalw, hivalign (lanl), genecutter (lanl) or NGlyAlign.

Have a nice week

--
a


From: Elma H. Akand ***@***.***>
Date: Monday, February 22, 2021 at 2:24 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: antoine ***@***.***>, Author ***@***.***>
Subject: Re: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)
Dear Antoine,
Thank you for your interest. My apology as due to the resource restriction, we are unable to it in mac or online. That is something we will try to resolve in the future.


Thanks,
Elma Akand
________________________________
From: antoine ***@***.***>
Sent: Saturday, 20 February 2021 7:16 AM
To: UNSW-Mathematical-Biology/NGlyAlign_v1.0 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UNSW-Mathematical-Biology/NGlyAlign_v1.0] install on Mac (#1)


Hello
I would be very interested in trying your tool. can it be deployed on a mac (or run online)?
thank you!
